defaults: &defaults
  twitter:
    api_key: ""
    api_secret: ""
    oauth_key: ""
    oauth_secret: ""

development:
  <<: *defaults

test:
  <<: *defaults

production:
  twitter:
    api_key: ""
    api_secret: ""